### ISSUE TITLE
`rgeos` package dependency

### ISSUE THREAD

**Issue by ajcanepa** [maRce10/PhenotypeSpace#10]
Hi there, 
I'm trying to install the `PhenotypeSpace` but I get the following error message:
```
ERROR: dependency ‘rgeos’ is not available for package ‘PhenotypeSpace’
```
The issue here is that `rgeos` package was removed from the CRAN repository (see [here](https://cran.r-project.org/web/packages/rgeos/index.html)) and alternatives like `terra` and/or `sf` package are provided by the CRAN message.

**Comment by maRce10** [comment]
thanks, I fixed it. It now uses `sf` instead
